FROM node:22-bookworm-slim AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
# Firebase Web values are public build configuration, never server secrets.
ARG VITE_FIREBASE_API_KEY
ARG VITE_FIREBASE_AUTH_DOMAIN
ARG VITE_FIREBASE_PROJECT_ID
ARG VITE_FIREBASE_APP_ID
ARG VITE_FIREBASE_STORAGE_BUCKET
ARG VITE_FIREBASE_MESSAGING_SENDER_ID
ARG VITE_FIREBASE_MEASUREMENT_ID
ARG VITE_FIRESTORE_DATABASE_ID
ARG VITE_PUBLIC_PROPERTY_ID
ARG VITE_STRIPE_PUBLISHABLE_KEY
ARG VITE_MERCADOPAGO_PUBLIC_KEY
ENV VITE_FIREBASE_API_KEY=$VITE_FIREBASE_API_KEY \
    VITE_FIREBASE_AUTH_DOMAIN=$VITE_FIREBASE_AUTH_DOMAIN \
    VITE_FIREBASE_PROJECT_ID=$VITE_FIREBASE_PROJECT_ID \
    VITE_FIREBASE_APP_ID=$VITE_FIREBASE_APP_ID \
    VITE_FIREBASE_STORAGE_BUCKET=$VITE_FIREBASE_STORAGE_BUCKET \
    VITE_FIREBASE_MESSAGING_SENDER_ID=$VITE_FIREBASE_MESSAGING_SENDER_ID \
    VITE_FIREBASE_MEASUREMENT_ID=$VITE_FIREBASE_MEASUREMENT_ID \
    VITE_FIRESTORE_DATABASE_ID=$VITE_FIRESTORE_DATABASE_ID \
    VITE_PUBLIC_PROPERTY_ID=$VITE_PUBLIC_PROPERTY_ID \
    VITE_STRIPE_PUBLISHABLE_KEY=$VITE_STRIPE_PUBLISHABLE_KEY \
    VITE_MERCADOPAGO_PUBLIC_KEY=$VITE_MERCADOPAGO_PUBLIC_KEY
# A production bundle cannot recover missing Vite values at runtime. Fail the
# image build before it can be pushed/deployed with an unusable Firebase client.
RUN test -n "$VITE_FIREBASE_API_KEY" \
    && test -n "$VITE_FIREBASE_AUTH_DOMAIN" \
    && test -n "$VITE_FIREBASE_PROJECT_ID" \
    && test -n "$VITE_FIREBASE_APP_ID" \
    && test -n "$VITE_FIREBASE_STORAGE_BUCKET" \
    && test -n "$VITE_FIREBASE_MESSAGING_SENDER_ID" \
    && test -n "$VITE_FIREBASE_MEASUREMENT_ID" \
    && test -n "$VITE_FIRESTORE_DATABASE_ID" \
    && test -n "$VITE_PUBLIC_PROPERTY_ID" \
    && npm run build

FROM node:22-bookworm-slim AS runtime
WORKDIR /app
ENV NODE_ENV=production
COPY package.json package-lock.json ./
RUN npm ci --omit=dev && npm cache clean --force
COPY --from=build /app/dist ./dist
EXPOSE 8080
CMD ["node", "dist/server.cjs"]
