import React, { useEffect, useState } from 'react';
import { canonicalRequest } from '../../services/canonicalPmsRuntime';

type Mode = 'pos' | 'finance' | 'staff' | 'projects';
type Envelope<T> = { success: boolean; data: T };
const title: Record<Mode, string> = { pos: 'PDV (Caixa)', finance: 'Financeiro', staff: 'Central de Equipe', projects: 'Projetos' };

/** Production-only management boundary. It deliberately renders only data
 * returned by tenant-scoped APIs; local DBState and fixtures never enter here. */
export const CanonicalManagementView: React.FC<{ mode: Mode }> = ({ mode }) => {
  const [records, setRecords] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [name, setName] = useState(''); const [amount, setAmount] = useState('');
  const path: Record<Mode, string> = { pos: '/api/management/pos/catalog', finance: '/api/management/finance/entries', staff: '/api/saas/staff', projects: '/api/management/projects' };
  useEffect(() => { let active = true; setLoading(true); canonicalRequest<Envelope<any[]>>(path[mode]).then(result => { if (active) setRecords(Array.isArray(result.data) ? result.data : []); }).catch(reason => { if (active) setError(reason.message || 'Dados indisponíveis'); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [mode]);
  const refresh = () => canonicalRequest<Envelope<any[]>>(path[mode]).then(result => setRecords(Array.isArray(result.data) ? result.data : []));
  const create = async (event: React.FormEvent) => { event.preventDefault(); try { if (mode === 'pos') await canonicalRequest('/api/management/pos/catalog', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name, category: 'geral', price: Number(amount), currency: 'BRL' }) }); if (mode === 'finance') await canonicalRequest('/api/management/finance/entries', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ type: 'expense', category: name, amount: Number(amount), currency: 'BRL', idempotencyKey: crypto.randomUUID() }) }); if (mode === 'projects') await canonicalRequest('/api/management/projects', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name, status: 'planned', priority: 'normal', currency: 'BRL', participantUserIds: [] }) }); setName(''); setAmount(''); await refresh(); } catch (reason: any) { setError(reason.message || 'Não foi possível salvar'); } };
  if (loading) return <div className="p-8 text-sm text-gray-600">Carregando dados operacionais…</div>;
  if (error) return <div className="mx-auto mt-10 max-w-xl rounded-2xl border border-gray-200 bg-white p-8 text-center"><h2 className="text-xl font-bold text-brand-dark">{title[mode]} indisponível</h2><p className="mt-3 text-sm text-gray-600">{error}</p></div>;
  return <section className="space-y-5"><header><h2 className="text-2xl font-bold text-brand-dark">{title[mode]}</h2><p className="text-sm text-gray-500">Dados canônicos da propriedade ativa</p></header>{mode !== 'staff' && <form onSubmit={create} className="flex flex-wrap gap-2 rounded-xl border border-gray-200 bg-white p-4"><input required value={name} onChange={e => setName(e.target.value)} className="input-base min-w-48 flex-1" placeholder={mode === 'projects' ? 'Nome do projeto' : 'Descrição'} />{mode !== 'projects' && <input required min="0" step="0.01" value={amount} onChange={e => setAmount(e.target.value)} type="number" className="input-base w-32" placeholder="Valor" />}<button className="btn-primary" type="submit">Adicionar</button></form>}{records.length === 0 ? <div className="rounded-xl border border-gray-200 bg-white p-8 text-center text-sm text-gray-600">Sem dados suficientes para esta propriedade.</div> : <div className="overflow-x-auto rounded-xl border border-gray-200 bg-white"><table className="min-w-full text-sm"><thead className="bg-gray-50 text-left text-gray-500"><tr><th className="px-4 py-3">Identificador</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Atualizado</th></tr></thead><tbody>{records.map(record => <tr key={record.itemId || record.saleId || record.entryId || record.userId || record.projectId} className="border-t"><td className="px-4 py-3 font-medium text-gray-800">{record.name || record.saleId || record.entryId || record.email || record.projectId}</td><td className="px-4 py-3">{record.status || (record.active === false ? 'inativo' : 'ativo')}</td><td className="px-4 py-3">{record.updatedAt || '—'}</td></tr>)}</tbody></table></div>}</section>;
};
